<?php // Lesson 5
// ENCAPSULATION

// PART 1

class Base
{
    public $a = "PUBLIC property!!!";
    protected $b = "PROTECTED property!!!";
    private $c = "PRIVATE property!!!";

    function printProperties(){
        echo "<br />" . $this->a;
        echo "<br />" . $this->b;
        echo "<br />" . $this->c;
        echo "<hr />";
    }
}

$obj1 = new Base();

//echo "<br />" . $obj1->a;
//echo "<br />" . $obj1->b;
//echo "<br />" . $obj1->c;
//echo "<hr />";

$obj1->printProperties();



// PART 2

class Inherited extends Base
{
    function printProperties()
    {
        parent::printProperties(); // TODO: Change the autogenerated stub

        // check 2 variants up and below

//        echo "<br />" . $this->a;
//        echo "<br />" . $this->b;
//        echo "<br />" . $this->c;
//        echo "<hr />";
    }
}

$obj2 = new Inherited();

//echo "<br />" . $obj2->a;
//echo "<br />" . $obj2->b;
//echo "<br />" . $obj2->c;
//echo "<hr />";

$obj2->printProperties();